name: Pull Request Test

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log Pull Request Event Github Context
        run: |
          echo '${{ toJSON(github) }}'
      - name: Log Pull Request Event
        run: |
          echo '${{ toJSON(github.event) }}'
