name: Workflow Dispatch and Push Test

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "This is a test input"
        type: number
        default: '5'
  push:

env:
  TEST_INPUT: ${{ case( github.event_name == 'workflow_dispatch', inputs.test_input, 5 ) }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Data
        run: |
          echo 'Inputs context: ${{ inputs }}'
          echo "Default TEST_INPUT: $TEST_INPUT"
          echo '${{ toJSON(github) }}'
