name: Push Test

on:
  push

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log Push Event Github Context
        run: |
          echo '${{ toJSON(github) }}'
      - name: Log Push Event
        run: |
          echo '${{ toJSON(github.event) }}'
